### ISSUE TITLE
strusInspect

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusUtilities#11]
Missing a command to list all feature types in the index (something like `attrnames` for attributes and `metatable` for metadata)

**Comment by andreasbaumann** [comment]
back-ported from strusWebService:

```
strusInspect -s 'path=storage' featuretypes
body
docid
subject
```

**Comment by andreasbaumann** [comment]
Committed a pull request: #12

**Comment by patrickfrey** [comment]
Temporary workaround:  dumpstorage with key prefix feature type 'T'.
     strusDumpStorage -P T -s path=storage
I will fix it as soon as possible

**Comment by patrickfrey** [comment]
you fixed it?

**Comment by andreasbaumann** [comment]
strusDumpStorage? This is strusInspect. And there is a pull request. :-)

**Comment by andreasbaumann** [comment]
Yep. And I didn't think about: `strusDumpStorage -P T -s path=storage`

**Comment by andreasbaumann** [comment]
The current solution seems only to produce feature types of the forward index, not
of the search index. Should there be two functions for this in the API and two commands
in strusInspect?
