### ISSUE TITLE
Documentation of the rule language in strusPatternMatcher

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusUtilities#53]
Maybe I'm just blind, but I don't see any documentation of the language in the *.rul file.

**Comment by patrickfrey** [comment]
Yes, the documentation is missing. I will provide some documentation soon.

**Comment by andreasbaumann** [comment]
http://www.project-strus.net/introduction_struspattern.htm

But I cannot find a link on the web page which references it.

**Comment by andreasbaumann** [comment]
There is a prominent link now on the main page.
