### ISSUE TITLE
strusPattern: sometimes corrupt match output

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusUtilities#65]
```
WORD ^ 1 : /\b\p{L}+\b/;
NUM ^ 1 : /\b[0-9]{1,12}\b/;
ORG ^ 2 : /\b(XXXX)\b/;

11 [61] : 4 ORG XXXX1
12 [66] : 2 NUMBER 41
```

the text contained:

```
He worked in department XXXX 41 from May 12th to...
```

**Comment by andreasbaumann** [comment]
It seems, when I add a capturing group around NUM  and WORD (the parts without \b), the ORG
match is only XXXX (which is correct).
So this means \b is part of the match?
Or should I always have capturing groups just to be sure?
Which capturing group would be taken?

**Comment by andreasbaumann** [comment]
for the rule:

``
Abreviation = sequence_imm( org = ORG, num = NUM );
```

all tokens printed seem to be ok in all cases.

**Comment by patrickfrey** [comment]
\b is part of the match. Grouping with ( ) has to be used to cut it away.

**Comment by andreasbaumann** [comment]
Ok, works for me. :-)
