### ISSUE TITLE
strusAnalyze shows nothing unless at least SearchIndex or ForwardIndex is declared

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusUtilities#8]
The following `strus.ana` configuration prints no output:

```
  [Attribute]
        docid = orig content /docs/doc/docid/();

  #[ForwardIndex]
  #    word = orig split /docs/doc/content/();

  #[SearchIndex]
  #       word = lc split /docs/doc/content/();

  [Document]
        doc = /docs/doc;
```

As soon as section `ForwardIndex` or `SearchIndex` is enabled, I also see
attribute and metadata output, otherwise not.

**Comment by patrickfrey** [comment]
Currently documents without search index features or forward index features are currently considered to be empty. I have changed that. I consider this bug as fixed.
